stages:
  - build
  - test
  - deploy

server_build:
  before_script:
  - cd ./server
  stage: build
  image: python:latest
  script: 
    - echo "Installing prerequisites..."
    - pip install -r requirements.txt
    - echo "Success!"
  
server_test:
  before_script:
    - cd ./server
    - echo "Installing prerequisites..."
    - pip install -r requirements.txt
  stage: test
  image: python:latest
  script:
    - echo "Running tests..."
    - pytest
    - echo "Success!"

server_deploy:
  before_script:
      - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
      - eval $(ssh-agent -s)
      - chmod 400 ./gitlab_rsa
      - ssh-add ./gitlab_rsa
      - mkdir -p ~/.ssh
      - chmod 700 ~/.ssh
  stage: deploy
  environment:
    name: staging
  script:
    - ssh -o StrictHostKeyChecking=no nnv2@nnv2.host.cs.st-andrews.ac.uk
    - cd ~/Documents/CS3099/project-code
    - git pull

    - cd server
    - python3 -m venv venv
    - source venv/bin/activate
    - pip3 install -r requirements.txt

    - flask db init
    - flask db upgrade

    - tmux kill-session -t CS3099
    - tmux new -s CS3099
    - gunicorn -b :5000 backend:app

    - cp ./deployment/nginx.conf /host/nnv2/nginx.d/default/backend.conf
    - nginx -c /host/<username>/nginx.conf -s reload
