stages:
  - build
  - test
  - deploy

server_build:
  before_script:
  - cd ./server
  stage: build
  image: python:latest
  script: 
    - echo "Installing prerequisites..."
    - pip install -r requirements.txt
    - echo "Success!"
  
server_test:
  before_script:
    - cd ./server
    - echo "Installing prerequisites..."
    - pip install -r requirements.txt
  stage: test
  image: python:latest
  script:
    - echo "Running tests..."
    - pytest
    - echo "Success!"

server_deploy:
  before_script:
      - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
      - eval $(ssh-agent -s)
      - chmod 400 ./gitlab_rsa
      - ssh-add ./gitlab_rsa
      - mkdir -p ~/.ssh
      - chmod 700 ~/.ssh
  stage: deploy
  environment:
    name: staging
  script:
    - ssh nnv2@nnv2.host.cs.st-andrews.ac.uk "mkdir working && exit"
