stages:
  - build
  - test
  - deploy

server_build:
  before_script:
  - cd ./server
  stage: build
  image: python:latest
  script: 
    - echo "Installing prerequisites..."
    - pip install -r requirements.txt
    - echo "Success!"
  
server_test:
  before_script:
    - cd ./server
    - echo "Installing prerequisites..."
    - pip install -r requirements.txt
  stage: test
  image: python:latest
  script:
    - echo "Running tests..."
    - pytest
    - echo "Success!"

server_deploy:
  before_script:
    - cd ./server
    - pip install -r requirements.txt
  stage: deploy
  image: python:latest
  environment:
    name: staging
  script:
    - flask db init
    - flask db migrate
    - flask db upgrade
    - flask run
